### ISSUE TITLE
Check out Phenix combine_models and see if we can use it for our scFv models

### ISSUE THREAD

**Issue by hemanyaradadia** [iGEMIISc/scFv-Modelling#1]

**Comment by hemanyaradadia** [comment]
Downloading Phenix required me to fill out an academic request form, which will take 2-3 days to process.

**Comment by mrigankpawagi** [comment]
I am not sure how, but it worked for me immediately (a couple of days back)!

**Comment by mrigankpawagi** [comment]
Phenix cannot be used since it requires MTZ (map) files which can only be experimentally obtained from what I understand. Please reopen the issue if you find anything else. We can use ProDy for now.
